services:
  - type: web
    name: elcira-marketplace
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false